# Generated by Django 3.2.3 on 2021-06-26 04:53

from django.db import migrations, models
import sub_part.models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_admin_opd_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_ipd',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=sub_part.models.filepath),
        ),
    ]
