# Generated by Django 3.2.3 on 2021-06-26 05:11

from django.db import migrations, models
import sub_part.models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_admin_ipd_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_patho_test',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=sub_part.models.filepath),
        ),
        migrations.AlterField(
            model_name='admin_patho_test',
            name='short_name',
            field=models.IntegerField(),
        ),
    ]
