# Generated by Django 3.2.3 on 2021-06-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_auto_20210626_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='department',
            field=models.EmailField(max_length=254),
        ),
    ]
